name: ouster-ros

on:
  push:
    branches:
      - ros2
  pull_request:
    branches:
      - ros2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up QEMU for Multi-Architecture Builds
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
          
      # - name: Build & Push ${{ matrix.arch }} the Docker image
      #   run: |
      #     docker login \
      #       -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p ${{ secrets.DOCKER_HUB_TOKEN }}
      #       docker build .                                    \
      #       --build-arg CPU_ARCH=${{ matrix.arch }} \
      #       --file Dockerfile                               \
      #       --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ matrix.arch }}-$GITHUB_SHA
      #     docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ matrix.arch }}-$GITHUB_SHA
